version: "3.7"
services:
  mysql-db:
    image: docker.io/mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # Garante UTF-8 como padrão no DB
    environment:
      "MYSQL_ROOT_PASSWORD": "dev_mode"
      "MYSQL_USER": "lfernando"
      "MYSQL_PASSWORD": "dev_mode"
      "MYSQL_DATABASE": "projectdb"
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
        
